# Generated by Django 3.1.2 on 2020-10-06 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201005_1425'),
        ('users', '0002_auto_20201006_1121'),
    ]

    operations = [
    ]
