# Generated by Django 3.1.1 on 2020-09-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('F', 'Fantasy'), ('B', 'Biography')], default=None, max_length=1),
        ),
    ]
