# Generated by Django 3.1.1 on 2020-09-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('F', 'Fantasy'), ('B', 'Biography'), ('O', 'Others')], default='O', max_length=1),
        ),
    ]
