# Generated by Django 3.1.1 on 2020-09-25 14:21

from django.db import migrations, models
import ecommerce_backend.api.books.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('F', 'Fantasy'), ('B', 'Biografia'), ('I', 'Inne')], max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('cover', models.ImageField(upload_to=ecommerce_backend.api.books.models.Book.generate_filename)),
            ],
            options={
                'db_table': 'books',
                'ordering': ['title'],
            },
        ),
    ]
